{
 "title": "GP5",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "5s",
 "panels": [
  { "title": "Products distribution", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Compliant and defective products distribution [number of pieces and percentage]",
   "type": "piechart",
   "gridPos": { "h": 13, "w": 8, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"local\")\n    |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n    |> filter(fn: (r) => r._field == \"value\" and r._value != \"\" and r._measurement == \"rfidOut1\") \n    |> group()\n    |> count(column: \"_value\")\n    |> rename(columns: {_value: \"Defective F\"})"
    },
    {
     "query": "from(bucket: \"local\")\n    |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n    |> filter(fn: (r) => r._field == \"value\" and r._value != \"\" and r._measurement == \"rfidOut2\") \n    |> group()\n    |> count(column: \"_value\")\n    |> rename(columns: {_value: \"Defective G\"})"
    },
    {
     "query": "from(bucket: \"local\")\n    |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n    |> filter(fn: (r) => r._field == \"value\" and r._value != \"\" and r._measurement == \"rfidOut3\") \n    |> group()\n    |> count(column: \"_value\")\n    |> rename(columns: {_value: \"Compliant\"})"
    }
   ]
  },
  {
   "title": "A1 compliant and defective products distribution [number of pieces and percentage]",
   "type": "piechart",
   "gridPos": { "h": 13, "w": 8, "x": 8, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"local\")\n    |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n    |> filter(fn: (r) => r._field == \"value\" and r._value == \"A1\" and r._measurement == \"rfidOut1\") \n    |> group()\n    |> count(column: \"_value\")\n    |> rename(columns: {_value: \"Defective F\"})"
    },
    {
     "query": "from(bucket: \"local\")\n    |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n    |> filter(fn: (r) => r._field == \"value\" and r._value == \"A1\" and r._measurement == \"rfidOut2\") \n    |> group()\n    |> count(column: \"_value\")\n    |> rename(columns: {_value: \"Defective G\"})"
    },
    {
     "query": "from(bucket: \"local\")\n    |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n    |> filter(fn: (r) => r._field == \"value\" and r._value == \"A1\" and r._measurement == \"rfidOut3\") \n    |> group()\n    |> count(column: \"_value\")\n    |> rename(columns: {_value: \"Compliant\"})"
    }
   ]
  },
  {
   "title": "A2 compliant and defective products distribution [number of pieces and percentage]",
   "type": "piechart",
   "gridPos": { "h": 13, "w": 8, "x": 16, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"local\")\n    |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n    |> filter(fn: (r) => r._field == \"value\" and r._value == \"A2\" and r._measurement == \"rfidOut1\") \n    |> group()\n    |> count(column: \"_value\")\n    |> rename(columns: {_value: \"Defective F\"})"
    },
    {
     "query": "from(bucket: \"local\")\n    |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n    |> filter(fn: (r) => r._field == \"value\" and r._value == \"A2\" and r._measurement == \"rfidOut2\") \n    |> group()\n    |> count(column: \"_value\")\n    |> rename(columns: {_value: \"Defective G\"})"
    },
    {
     "query": "from(bucket: \"local\")\n    |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n    |> filter(fn: (r) => r._field == \"value\" and r._value == \"A2\" and r._measurement == \"rfidOut3\") \n    |> group()\n    |> count(column: \"_value\")\n    |> rename(columns: {_value: \"Compliant\"})"
    }
   ]
  },
  {
   "title": "Compliant and defective products distribution per minute [number of pieces]",
   "type": "barchart",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 14 },
   "targets": [
    {
     "query": "from(bucket: \"local\")\n    |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n    |> filter(fn: (r) => r._field == \"value\" and r._value != \"\" and r._measurement == \"rfidOut1\")\n    |> aggregateWindow(every: 1m, fn: count)\n    |> rename(columns: {_value: \"Defective F\"})"
    },
    {
     "query": "from(bucket: \"local\")\n    |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n    |> filter(fn: (r) => r._field == \"value\" and r._value != \"\" and r._measurement == \"rfidOut2\")\n    |> aggregateWindow(every: 1m, fn: count)\n    |> rename(columns: {_value: \"Defective G\"})"
    },
    {
     "query": "from(bucket: \"local\")\n    |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n    |> filter(fn: (r) => r._field == \"value\" and r._value != \"\" and r._measurement == \"rfidOut3\")\n    |> aggregateWindow(every: 1m, fn: count)\n    |> rename(columns: {_value: \"Compliant\"})"
    }
   ]
  },
  { "title": "Production time", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 24 } },
  {
   "title": "Production time per compliant product [ms]",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 18, "x": 0, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "query": "from(bucket: \"local\")\n    |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n    |> filter(fn: (r) => r._field == \"value\" and r._value != \"\" and r._measurement == \"durationMsA1\")\n    |> toInt()\n\n"
    },
    {
     "query": "from(bucket: \"local\")\n    |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n    |> filter(fn: (r) => r._field == \"value\" and r._value != \"\" and r._measurement == \"durationMsA2\")\n    |> toInt()\n\n"
    }
   ]
  },
  {
   "title": "Average production time A1 compliant pieces [ms]",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 25 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "query": "from(bucket: \"local\")\n    |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n    |> filter(fn: (r) => r._field == \"value\" and r._value != \"\" and r._measurement == \"durationMsA1\")\n    |> toInt()\n\n"
    }
   ]
  },
  {
   "title": "Average production time A2 compliant pieces [ms]",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 31 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "query": "from(bucket: \"local\")\n    |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n    |> filter(fn: (r) => r._field == \"value\" and r._value != \"\" and r._measurement == \"durationMsA2\")\n    |> toInt()\n\n"
    }
   ]
  },
  { "title": "Machines utilization rate", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 37 } },
  {
   "title": "R1 utilization rate [percentage]",
   "type": "piechart",
   "gridPos": { "h": 9, "w": 6, "x": 0, "y": 38 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"local\")\n    |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n    |> filter(fn: (r) => r._measurement == \"photocellR1\" and r._field == \"value\")\n    |> filter(fn: (r) => r._value == 1)\n    |> group()\n    |> count(column: \"_value\")\n    |> rename(columns: {_value: \"Working\"})"
    },
    {
     "query": "from(bucket: \"local\")\n    |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n    |> filter(fn: (r) => r._measurement == \"photocellR1\" and r._field == \"value\")\n    |> filter(fn: (r) => r._value == 0)\n    |> group()\n    |> count(column: \"_value\")\n    |> rename(columns: {_value: \"Idle\"})"
    }
   ]
  },
  {
   "title": "R2 utilization rate [percentage]",
   "type": "piechart",
   "gridPos": { "h": 9, "w": 6, "x": 6, "y": 38 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"local\")\n    |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n    |> filter(fn: (r) => r._measurement == \"photocellR2\" and r._field == \"value\")\n    |> filter(fn: (r) => r._value == 1)\n    |> group()\n    |> count(column: \"_value\")\n    |> rename(columns: {_value: \"Working\"})"
    },
    {
     "query": "from(bucket: \"local\")\n    |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n    |> filter(fn: (r) => r._measurement == \"photocellR2\" and r._field == \"value\")\n    |> filter(fn: (r) => r._value == 0)\n    |> group()\n    |> count(column: \"_value\")\n    |> rename(columns: {_value: \"Idle\"})"
    }
   ]
  },
  {
   "title": "R3 utilization rate [percentage]",
   "type": "piechart",
   "gridPos": { "h": 9, "w": 6, "x": 12, "y": 38 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"local\")\n    |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n    |> filter(fn: (r) => r._measurement == \"photocellR3\" and r._field == \"value\")\n    |> filter(fn: (r) => r._value == 1)\n    |> group()\n    |> count(column: \"_value\")\n    |> rename(columns: {_value: \"Working\"})"
    },
    {
     "query": "from(bucket: \"local\")\n    |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n    |> filter(fn: (r) => r._measurement == \"photocellR3\" and r._field == \"value\")\n    |> filter(fn: (r) => r._value == 0)\n    |> group()\n    |> count(column: \"_value\")\n    |> rename(columns: {_value: \"Idle\"})"
    }
   ]
  },
  {
   "title": "R4 utilization rate [percentage]",
   "type": "piechart",
   "gridPos": { "h": 9, "w": 6, "x": 18, "y": 38 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"local\")\n    |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n    |> filter(fn: (r) => r._measurement == \"photocellR4\" and r._field == \"value\")\n    |> filter(fn: (r) => r._value == 1)\n    |> group()\n    |> count(column: \"_value\")\n    |> rename(columns: {_value: \"Working\"})"
    },
    {
     "query": "from(bucket: \"local\")\n    |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n    |> filter(fn: (r) => r._measurement == \"photocellR4\" and r._field == \"value\")\n    |> filter(fn: (r) => r._value == 0)\n    |> group()\n    |> count(column: \"_value\")\n    |> rename(columns: {_value: \"Idle\"})"
    }
   ]
  },
  {
   "title": "R5 utilization rate [percentage]",
   "type": "piechart",
   "gridPos": { "h": 9, "w": 6, "x": 0, "y": 47 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"local\")\n    |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n    |> filter(fn: (r) => r._measurement == \"photocellR5\" and r._field == \"value\")\n    |> filter(fn: (r) => r._value == 1)\n    |> group()\n    |> count(column: \"_value\")\n    |> rename(columns: {_value: \"Working\"})"
    },
    {
     "query": "from(bucket: \"local\")\n    |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n    |> filter(fn: (r) => r._measurement == \"photocellR5\" and r._field == \"value\")\n    |> filter(fn: (r) => r._value == 0)\n    |> group()\n    |> count(column: \"_value\")\n    |> rename(columns: {_value: \"Idle\"})"
    }
   ]
  },
  {
   "title": "First camera inspection utilization rate [percentage]",
   "type": "piechart",
   "gridPos": { "h": 9, "w": 6, "x": 6, "y": 47 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"local\")\n    |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n    |> filter(fn: (r) => r._measurement == \"photocellFirstQC\" and r._field == \"value\")\n    |> filter(fn: (r) => r._value == 1)\n    |> group()\n    |> count(column: \"_value\")\n    |> rename(columns: {_value: \"Working\"})"
    },
    {
     "query": "from(bucket: \"local\")\n    |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n    |> filter(fn: (r) => r._measurement == \"photocellFirstQC\" and r._field == \"value\")\n    |> filter(fn: (r) => r._value == 0)\n    |> group()\n    |> count(column: \"_value\")\n    |> rename(columns: {_value: \"Idle\"})"
    }
   ]
  },
  {
   "title": "Oven utilization rate [percentage]",
   "type": "piechart",
   "gridPos": { "h": 9, "w": 6, "x": 12, "y": 47 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"local\")\n    |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n    |> filter(fn: (r) => r._measurement == \"photocellOven\" and r._field == \"value\")\n    |> filter(fn: (r) => r._value == 1)\n    |> group()\n    |> count(column: \"_value\")\n    |> rename(columns: {_value: \"Working\"})"
    },
    {
     "query": "from(bucket: \"local\")\n    |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n    |> filter(fn: (r) => r._measurement == \"photocellOven\" and r._field == \"value\")\n    |> filter(fn: (r) => r._value == 0)\n    |> group()\n    |> count(column: \"_value\")\n    |> rename(columns: {_value: \"Idle\"})"
    }
   ]
  },
  {
   "title": "Second camera inspection utilization rate [percentage]",
   "type": "piechart",
   "gridPos": { "h": 9, "w": 6, "x": 18, "y": 47 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"local\")\n    |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n    |> filter(fn: (r) => r._measurement == \"photocellSecondQC\" and r._field == \"value\")\n    |> filter(fn: (r) => r._value == 1)\n    |> group()\n    |> count(column: \"_value\")\n    |> rename(columns: {_value: \"Working\"})"
    },
    {
     "query": "from(bucket: \"local\")\n    |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n    |> filter(fn: (r) => r._measurement == \"photocellFirstQC\" and r._field == \"value\")\n    |> filter(fn: (r) => r._value == 0)\n    |> group()\n    |> count(column: \"_value\")\n    |> rename(columns: {_value: \"Idle\"})"
    }
   ]
  },
  { "title": "WIP", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 56 } },
  {
   "title": "WIP [number of pieces]",
   "type": "gauge",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 57 },
   "targets": [
    {
     "query": "in = from(bucket: \"local\")\n    |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n    |> filter(fn: (r) => r._measurement == \"rfidIn\" and r._field == \"value\")\n    |> filter(fn: (r) => r._value != \"\")\n    |> group()\n    |> count(column: \"_value\")\n\nout = from(bucket: \"local\")\n    |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n    |> filter(fn: (r) => r._field == \"value\" and r._value != \"\" and (r._measurement == \"rfidOut1\" or r._measurement == \"rfidOut2\" or r._measurement == \"rfidOut3\") )\n    |> group()\n    |> count(column: \"_value\")\n\nresult = union(tables: [in, out])\n    |> sort()\n    |> difference()\n\nresult"
    }
   ]
  },
  {
   "title": "Entering pieces [number of pieces]",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 12, "y": 57 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"local\")\n    |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n    |> filter(fn: (r) => r._measurement == \"rfidIn\" and r._field == \"value\")\n    |> filter(fn: (r) => r._value == \"A2\" or r._value == \"A1\")\n    |> count(column: \"_value\")"
    }
   ]
  },
  {
   "title": "Exiting pieces [number of pieces]",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 18, "y": 57 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"local\")\n    |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n    |> filter(fn: (r) => r._field == \"value\" and r._value != \"\" and (r._measurement == \"rfidOut1\" or r._measurement == \"rfidOut2\" or r._measurement == \"rfidOut3\") )\n    |> group()\n    |> count(column: \"_value\")"
    }
   ]
  }
 ]
}